# -*- coding: utf-8 -*-
"""Calculo_de_Raizes_Bhaskara.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNIv9z4X22dEqojRAMD7IzOxqhMMN5qq
"""

import math

print(' ----------- Calculo de raizes Bhaskara -----------\n')

a = float(input('valor de a: '))
b = float(input('valor de b: '))
c = float(input('valor de c: '))

delta = b ** 2 - 4 * a * c

if (delta < 0):
  print('não existe raiz!!!')

if (delta == 0):
  raizX1 = (-b + math.sqrt(delta)) / (2 * a)
  print('Existe apenas uma raiz!', raizX1)
else:
  if (delta > 0):
    raizX1 = (-b + math.sqrt(delta)) / (2 * a)
    raizX2 = (-b - math.sqrt(delta)) / (2 * a)
    print('raiz x1:',raizX1, 'raiz x2:', raizX2)