# -*- coding: utf-8 -*-
"""Praticar_Tarefa_de_Programação_Exercício_Conversor_de_Segundos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q1afvtagSPezst5xwuUy19srOsNimSev
"""

seconds = input('Por favor, entre com o número de segundos que deseja converter: ')
total_sec = int(seconds)

days = total_sec // 86400
hours = total_sec // 3600
sec_restantes = total_sec % 3600
minutes = sec_restantes // 60
sec_restantes_final = sec_restantes % 60

if (total_sec == 0):
  print(' -------- ZERO SEGUNDOS NÃO EXISTE -------- ')

if (days == 0): 
  print(days, 'dia,', hours, 'horas,', minutes, 'minutos e', sec_restantes_final, 'segundos.')

if (total_sec > 3600): 
  hours = (total_sec // 3600 ) - (24 * days)
  print(days, 'dia,', hours, 'horas,', minutes, 'minutos e', sec_restantes_final, 'segundos.')
