# -*- coding: utf-8 -*-
"""Fatorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZcK-Ukwwok8gOrFZY27wqtmfVb3MDws
"""

x = int(input("Digite o valor de n: ") )

resultado = 1
i = 1

while i <= x:
    resultado *= i
    i += 1

print(resultado)