# -*- coding: utf-8 -*-
"""TarefaDeProgramaçãoCoursera_Lista_1_media_aritmerica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fc9yw3TPAog3kNt9BCsU-98_oMZpVCO
"""

def mediaArtimetica (nota1, nota2, nota3, nota4):
  return (nota1 + nota2 + nota3 + nota4) / 4

nota1 = float(input('Insira sua primeira nota: '))
nota2 = float(input('Insira sua segunda nota: '))
nota3 = float(input('Insira sua terceira nota: '))
nota4 = float(input('Insira sua quarta nota: '))

print(f'Sua média é: {mediaArtimetica(nota1, nota2, nota3, nota4)}')