# -*- coding: utf-8 -*-
"""Praticar_Tarefa_de_Programação_Exercício_Digito_das_Dezenas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LcScrg5jrzOfuZ3__VZxbWV6CSA2cDB0
"""

n = int(input('Digite um número inteiro: ')) 

d = (n // 10) % 10 

print('O dígito das dezenas é: ',d)