# -*- coding: utf-8 -*-
"""Soma_dos_Números_de_Um_Número_Inteiro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZcK-Ukwwok8gOrFZY27wqtmfVb3MDws
"""

x = int(input("Digite um número inteiro: "))
y = x % 10 
z = (x // 10) % 10
w = (x / 10) // 10
print(y + z + w)