# -*- coding: utf-8 -*-
"""Ímpares.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZcK-Ukwwok8gOrFZY27wqtmfVb3MDws
"""

x = int(input("Digite o valor de n: "))

i = 1

while i <= (x+x):
  if i % 2 != 0:
    print(i)
    i += 1
  else:
    i += 1